export const Screens = {
    TAB_VIEW: 'tabView',
    ON_BOARDING_SCREEN: 'OnBoarding',
    WELCOME_SCREEN: 'WelcomeScreen',
    PERSONALIZED_WELCOME_SCREEN: 'PersonalizedWelcomeScreen',
    SELECT_STATE_SCREEN: 'SelectStateScreen',
    DIFFICULTIES_SCREEN: 'DifficultiesScreen',
    PROVIDER_INTEREST_SCREEN: 'ProviderInterestScreen',
    LIFE_EVENTS_SCREEN: 'LifeEventsScreen',
    REAL_PERSON_SCREEN: 'RealPersonScreen',
    TIME_OF_DAY_SCREEN: 'TimeOfDayScreen',
    ACCESS_AND_QUALITY_SCREEN: 'AccessAndQualityScreen',
    CONTRIBUTION_GATE_SCREEN: 'ContributionGateScreen',
    PATIENT_ON_BOARDING_SCREEN: 'PatientOnBoarding',
    UPDATE_PROFILE_SCREEN: 'UpdateProfile',
    CHAT_CONTACT_LIST: 'chatContactList',
    CHAT_INSTANCE: 'chatInstance',
    EDUCATIONAL_CONTENT_PIECE: 'EducationalContentPiece',
    VIDEO_CALL: 'VideoCall',
    TELE_SESSION_V2: 'TelehealthSessionV2Screen',
    PROVIDER_LIST_SCREEN: 'ProviderListScreen',
    PROVIDER_DETAIL_SCREEN: 'ProviderDetailScreen',
    LIVE_CHAT_WINDOW_SCREEN: 'LiveChatWindow',
    PROGRESS_REPORT_SCREEN: 'ProgressReportScreen',
    PROGRESS_REPORT_SEE_ALL_SCREEN: 'ProgressReportSeeAllScreen',
    PRIVACY_POLICY_SCREEN: 'PrivacyPolicy',
    SUPPORT_SCREEN: 'Support',
    ABOUT_SCREEN: 'AboutScreen',
    TERMS_OF_SERVICE_SCREEN: 'TermsOfService',
    PROVIDER_SEARCH: 'ProviderSearch',
    COMPLETED_SESSION: 'CompletedSessionScreen',
    PRIVATE_FEEDBACK_SCREEN: 'PrivateFeedbackScreen',
    PUBLIC_FEEDBACK_SCREEN: 'PublicFeedbackScreen',
    SEND_FEEDBACK_SCREEN: 'SendFeedbackScreen',
    TELEHEALTH_WELCOME: 'TelehealthWelcomeScreen',
    PROVIDER_ACCESS_SCREEN: 'ProviderAccessScreen',
    INVITATION: 'InvitationScreen',
    CONNECTIONS_SCREEN: 'ConnectionScreen',
    REVIEW_DETAIL_SCREEN: 'ReviewDetailScreen',
    TOPIC_CONTENT_LIST_SCREEN: 'TopicContentListScreen',
    TOPIC_LIST_SCREEN: 'TopicListScreen',
    WAITING_ROOM_SCREEN: 'WaitingRoomScreen',
    PENDING_CONNECTIONS_SCREEN: 'PendingConnectionScreen',
    DCT_REPORT_VIEW_SCREEN: 'DCTReportViewScreen',
    OUTCOME_DETAIL_SCREEN: 'OutcomeDetailScreen',
    ASSIGNABLE_CONTENT_LIST: 'AssignableContentList',
    TAKE_ASSESSMENT_SCREEN: 'TakeAssessmentScreen',
    PROGRESS_REPORT_SEE_ALL_SCREEN_DCT: 'ProgressReportSeeAllScreenDct',
    FEEDBACK_SCREEN: 'FeedbackScreen',
    APPT_PATIENT_INFORMATION_SCREEN: 'PatientInformationScreen',
    REQUEST_APPT_SELECT_PROVIDER_SCREEN: 'AppointmentSelectProviderScreen',
    REQUEST_APPT_SELECT_SERVICE_SCREEN: 'AppointmentSelectServiceScreen',
    REQUEST_APPT_SELECT_DATE_TIME_SCREEN: 'AppointmentSelectDateTimeScreen',
    REQUEST_APPT_CONFIRM_DETAILS_SCREEN: 'AppointmentConfirmDetailsScreen',
    REQUEST_APPT_STATE_CONSENT_SCREEN: 'ApptStateLimitedConsentScreen',
    REQUEST_APPT_STATE_CONSENT_REJECTION_SCREEN: 'ApptStateLimitedConsentRejectionScreen',
    REQUEST_APPT_EDIT_MESSAGE_SCREEN: 'AppointmentEditMessageScreen',
    APPOINTMENT_SUBMITTED: 'AppointmentSubmitted',
    APPOINTMENTS_SCREEN: 'AppointmentsScreen',
    SETTINGS_SCREEN: 'SettingsScreen',
    APPOINTMENT_DETAILS_SCREEN: 'AppointmentDetailsScreen',
    NOTIFICATION_SCREEN: 'NotificationScreen',
    PAYMENT_SCREEN: 'PaymentCardScreen',
    REMINDERS_SCREEN: 'RemindersScreen',
    SECTION_LIST_SCREEN: 'SectionListScreen',
    CHATBOT_PROFILE: 'ChatbotProfileScreen',
    SESSION_COST_SCREEN: 'SessionCostScreen',
    SESSION_PAID_SCREEN: 'SessionPaidScreen',
    MEMBER_PROFILE_SCREEN: 'MemberProfileScreen',
    CARD_LIST_SCREEN: 'CardListScreen',
    INVOICE_SCREEN: 'InvoiceScreen',
    CREATE_GROUP_SCREEN: 'CreateGroupScreen',
    ADD_MEMBERS_SCREEN: 'AddMembersScreen',
    GROUP_DETAIL_SCREEN: 'GroupDetailScreen',
    MATCH_MAKER_DETAIL_SCREEN: 'MatchMakerDetailScreen',
    TYPE_FORM_SCREEN: 'TypeFormScreen',
    SERVICE_LIST_SCREEN: 'ServiceListScreen',
    MY_WALLET_SCREEN: 'MyWalletScreen',
    GROUP_CALL_SCREEN: 'GroupCallScreen',
    MAGIC_LINK_SCREEN: 'MagicLinkScreen',
    SENT_MAGIC_LINK_SCREEN: 'SentMagicLinkScreen',
    ENTER_NAME_SCREEN: 'EnterNameScreen',
    SELECT_GOALS_SCREEN: 'SelectGoalsScreen',
    ENTER_DATE_OF_BIRTH: 'EnterDateOfBirthScreen',
    ENTER_ZIP_CODE_SCREEN: 'EnterZipCodeScreen',
    ENTER_PROVIDER_CODE_SCREEN: 'EnterProviderCodeScreen',
    EXCLUSION_CRITERIA_SCREEN: 'ExclusionCriteriaScreen',
    EMERGENCY_SERVICE_SCREEN: 'EmergencyServiceScreen',
    PROFILE_IMAGE_SCREEN: 'ProfileImageScreen',
    SIGNUP_NOTIFICATION_SCREEN: 'SignupNotificationsScreen',
    CONSENT_SCREEN: 'ConsentScreen',
    GROUP_RULES_ACCEPT_SCREEN: 'GroupRulesAcceptScreen',
    GENERIC_PAYMENT_SCREEN: 'GenericPaymentScreen',
    GENERIC_MEDIA_VIEW: 'GenericMediaViewScreen',
    ALFIE_QUESTION_SCREEN: 'AlfieQuestionScreen',
    REWARD_POINTS_SCREEN: 'RewardPointsScreen',
    SUBSCRIPTION_REQUIRED_SCREEN: 'SubscriptionRequiredScreen',
    PRIVACY_DISCLOSURE_SCREEN: 'PrivacyDisclosureScreen',
    APPT_SELECT_SERVICE_TYPE_SCREEN: 'SelectServiceTypeScreen',
    APPT_SELECT_SERVICE_BY_TYPE_SCREEN: 'SelectServiceByTypeScreen',
    GROUP_DONATION_SCREEN: 'GroupDonationScreen',
    GROUP_PAY_IT_FORWARD_SCREEN: 'GroupPayItForwardScreen',
    GROUP_CONTRIBUTION_SCREEN: 'GroupContributionScreen',
    GROUP_REWARD_POINTS_SCREEN: 'GroupRewardPointsScreen',
    POST_SESSION_CONTRIBUTION_SCREEN: 'PostSessionContributionScreen',
    COMMUNITY_CONGRATS_SCREEN: 'CommunityCongratsScreen',
    CONFIRM_AND_PAY_SCREEN: 'ConfirmAndPayScreen',
    ADD_PAYMENT_METHOD_AND_PAY_SCREEN: 'AddPaymentMethodAndPayScreen',
    ON_BOARDING_CONTRIBUTION_SCREEN: 'onBoardingContributionScreen',
    MY_CARE_TEAM_SCREEN: 'MyCareTeamScreen',
    MY_CONTRIBUTION_SCREEN: 'MyContributionScreen',
    APPT_SELECT_SERVICE_DETAIL_SCREEN : 'ApptSelectServiceByTypeDetailScreen',
    NEW_APPT_DETAILS_SCREEN : 'NewApptDetailsScreen',
    PROVIDER_FEEDBACK_SCREEN : 'ProviderFeedbackScreen',
    NEW_CHAT_UI_ITEMS_SCREEN : 'NewChatUiItemsScreen',
    EDUCATION_READ_DETAILS_SCREEN : 'EducationReadDetailsScreen',
    NEW_PAYMENT_DETAILS_SCREEN : 'NewPaymentDetailsScreen',
    COMMUNITY_PAYMENT_SCREEN : 'CommunityPaymentScreen',
    SESSION_REWARD_SCREEN : 'SessionRewardScreen',
    CHATBOT_ACTIVITY_SCREEN : 'ChatBotActivity',
    CHATBOT_LIST_SCREEN: 'ChatBotListScreen',
    GROUP_ACTIVITY_SCREEN : 'GroupActivityScreen',
    EXCLUSION_CRITERIA_FOR_CLINICIANS_SCREEN: 'ExclusionCriteriaForCliniciansScreen',
    EXCLUSION_CRITERIA_NOT_PASSED_SCREEN: 'ExclusionCriteriaNotPassedScreen',
    ALL_GROUPS_SCREEN : 'AllGroupsScreen',
    NEW_GROUP_DETAILS_SCREEN : 'NewGroupDetailsScreen',
    NEW_GROUP_CONTRIBUTION_SCREEN : 'NewGroupContributionScreen',
    NEW_CONTRIBUTION_DONE_SCREEN : 'NewContributionDoneScreen',
    REVAMP_TYPE_HOME_SCREEN: 'RevampTypeHomeScreen',
    REVAMP_QUESTIONS_SCREEN: 'RevampQuestionsScreen',
    REVAMP_REWARD_POINT_SCREEN: 'RevampRewardPointScreen',
    REVAMP_ON_BOARDING_HOME: 'RevampOnBoardingHomeScreen',
    REVAMP_HOME: 'RevampHomeScreen',
    REVAMP_ON_BOARDING_PROGRESS_SCREEN: 'RevampOnBoardingProgressScreen',
    REVAMP_SCHEDULE_ACTIVITY: 'RevampScheduleActivityScreen',
    REVAMP_CHECK_IN_ACTIVITY: 'RevampCheckInActivityScreen',
    REVAMP_PLAN_ONBOARDING: 'RevampPlanOnboardingScreen',
    ADD_YOUR_PRIORITIES_SCREEN: 'AddToYourPrioritiesScreen',
    PLAN_HOME_DETAILS_SCREEN: 'PlanHomeDetailsScreen',
    REVAMP_ALL_ACTIVITIES_SCREEN: 'RevampAllActivitiesScreen',
    REVAMP_ADD_ACTIVITIES_SCREEN: 'RevampAddActivitiesScreen',
    REVAMP_TOKEN_SPINNER_SCREEN: 'RevampTokenSpinnerScreen',
    SUNDAY_CHECK_IN_HOME_SCREEN: 'SundayCheckInHomeScreen',
    REVAMP_SUNDAY_CHECK_IN_QUESTIONS_SCREEN: 'RevampSundayCheckInQuestionsScreen',
    REVAMP_PLAN_SUNDAY_CHECKIN_SCREEN: 'RevampPlanSundayCheckInScreen',
    CUSTOM_CHAT_VIEW : 'CustomChatView',
    APPOINTMENT_PAYMENT_OPTIONS_SCREEN : 'ApptPaymentOptionsScreen',
    APPOINTMENT_INSURANCE_LIST_SCREEN : 'ApptInsuranceListScreen',
    APPOINTMENT_OTHER_INSURANCE_OPTIONS_LIST_SCREEN : 'ApptOtherInsuranceOptionsListScreen',
    APPOINTMENT_ACTUAL_PRICE_SCREEN: 'ApptActualPriceScreen',
   REVAMP_PROGRESS_REPORT_SCREEN: 'RevampProgressReportScreen',
    PATIENT_PROHIBITIVE_SCREEN : 'PatientProhibitiveScreen',
    CHOOSE_PATH_SCREEN: 'ChoosePathScreen',
    MATCH_MAKER_SCREEN: 'MatchMakerScreen',
    ENTER_EMAIL_SCREEN: 'EnterEmailScreen',
    SCHEDULE_SCREEN: 'ScheduleScreen',
    ENTER_PHONE_SCREEN: 'EnterPhoneScreen',
    SUBSCRIPTION_PACKAGE_SCREEN: 'SubscriptionPackageScreen',
};
